### ISSUE TITLE
accessing my metadata

### ISSUE THREAD

**Issue by jedineeper** [hashicorp/atlas-upload-cli#15]
If I do `atlas-upload -metadata="test=123" jedineeper/au-test test.tgz` it uploads the file to Atlas and the debug indicates the metadata has been uploaded.

Is it possible to access that metadata again once its in Atlas so it can be passed forward onto an associated packer build?

**Comment by justincampbell** [comment]
We'll definitely get to this very soon. Thanks!

**Comment by jedineeper** [comment]
Hi Justin,

Any word on this?

Thanks!

**Comment by justincampbell** [comment]
Closing this, as the Atlas Artifact Registry has been deprecated. Thanks!
