### ISSUE TITLE
`<username>/app` instead of `app` as argument

### ISSUE THREAD

**Issue by bitgeeky** [hashicorp/atlas-upload-cli#8]
The package requires to pass in `<username>/app_name` but documentation asks to pass in just `app_name` in `atlas-upload app path`.

Error:
```
Pankajs-MacBook-Pro:app bitgeeky$ pwd
/Users/bitgeeky/Sites/travis-to-atlas/app
Pankajs-MacBook-Pro:app bitgeeky$ atlas-upload simple /Users/bitgeeky/Sites/travis-to-atlas/app
error starting upload: upload: malformed slug "simple"
Pankajs-MacBook-Pro:app bitgeeky$
```
whereas on passing `bitgeeky/simple` it works fine.
Could you please confirm this, so that I/someone can update the `atlas-upload -h` guide.

**Comment by sethvargo** [comment]
It should be "slug", not app. Tagging.
