### ISSUE TITLE
Include patterns may not behave as expected

### ISSUE THREAD

**Issue by gwilym** [hashicorp/atlas-upload-cli#9]
Example file structure:

```
build/
build/linux-amd64/
build/linux-amd64/appname
build/darwin-amd64/
build/darwin-amd64/appname
```

When running the uploader from the directory containing `build` ...

Pattern specified:

`-input=build/*/*`

Expected:

That the `appname` files would be included.

Actual:

`build` is skipped in `copyDirWalkFn`, and it's children are not visited for pattern matching.

Workaround:

Specify `-include=build -include=build/* -include=build/*/*`

Generally, the behaviour of `include` isn't well-defined, so this may be a wild assumption. The "problem" for me being that this leaked through to Vagrant / Atlas -related confusion. Luckily I was able to dig through to here and find the problem, I just didn't write a solution because I don't know the intended behaviour.

**Comment by sethvargo** [comment]
@KFishner is this related to what you were seeing the other day in Packer?

**Comment by KFishner** [comment]
Yeah this is the same functionality for Packer push. 

@mitchellh what's the UX that you intended here? Should including the folder send all the children files and folders as well?

**Comment by mitchellh** [comment]
Fixed!

**Comment by sethvargo** [comment]
"It was pretty sad, I did it in the airplane for maximum sadness" - @mitchellh
